[package]
name = "bq24259"
version = "0.1.0"
edition = "2021"
keywords = ["embedded-hal"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.14"
embedded-hal = "1.0"
